name = "simple-forms"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2025-08-23"
compatibility_flags = ["nodejs_compat"]

[assets]
binding = "ASSETS"
directory = "".svelte-kit/cloudflare"
